app: save-up

tenant: sporto

service:
  name: save-up

provider:
  name: aws
  apiName: save-up-api
  stackName: save-up-api
  region: us-east-1
  runtime: rust
  environment:
    SYSTEM_EMAIL: ${env:SYSTEM_EMAIL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "arn:aws:ses:us-east-1:*:*"

plugins:
  # this adds informs servleress to use
  # the serverless-rust plugin
  - serverless-rust
# creates one artifact for each function

package:
  individually: true

functions:
  hello:
    handler: hello
  mail:
    handler: mail
    events:
      - sns: emails
